version: "3.9"

volumes:
  postgres-data: null

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=localPassword
      - POSTGRES_DB=blog_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
